version: '3'
networks:
  frontend: 
    driver: bridge
services:
  nginx-proxy:
    build:
      context: .
      dockerfile: nginx/DOCKERFILE
    image: 'nginx-proxy:latest'
    restart: always
    networks:
      - frontend
    ports:
      - '9000:80'
  calc-main:
    build:
      context: .
      dockerfile: docker/calc_main.dockerfile
    image: 'calc-main:latest'
    restart: always
    networks: 
      - frontend
    ports:
      - '9001:80'
  calc-micro:
    build:
      context: .
      dockerfile: docker/calc_micro.dockerfile
    image: 'calc-micro:latest'
    restart: always
    ports:
      - '9002:80'
    networks: 
      - frontend
  date-micro:
    build:
      context: .
      dockerfile: docker/date_micro.dockerfile
    image: 'date-micro:latest'
    restart: always
    ports:
      - '9003:80'
    networks: 
      - frontend
  date-main:
    build:
      context: .
      dockerfile: docker/date_main.dockerfile
    image: 'date-main:latest'
    restart: always
    networks: 
      - frontend
    ports:
      - '9004:80'
